/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/components/Dashboard/Card`; params?: Router.UnknownInputParams; } | { pathname: `/components/Dashboard/ServiceCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/Dashboard/ServicesList`; params?: Router.UnknownInputParams; } | { pathname: `/components/Dashboard/TopNavigation`; params?: Router.UnknownInputParams; } | { pathname: `/components/Dashboard/TransactionCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/Dashboard/TransactionsList`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/TopNavigation`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Dashboard/Card`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Dashboard/ServiceCard`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Dashboard/ServicesList`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Dashboard/TopNavigation`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Dashboard/TransactionCard`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Dashboard/TransactionsList`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/TopNavigation`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/components/Dashboard/Card${`?${string}` | `#${string}` | ''}` | `/components/Dashboard/ServiceCard${`?${string}` | `#${string}` | ''}` | `/components/Dashboard/ServicesList${`?${string}` | `#${string}` | ''}` | `/components/Dashboard/TopNavigation${`?${string}` | `#${string}` | ''}` | `/components/Dashboard/TransactionCard${`?${string}` | `#${string}` | ''}` | `/components/Dashboard/TransactionsList${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/TopNavigation${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/components/Dashboard/Card`; params?: Router.UnknownInputParams; } | { pathname: `/components/Dashboard/ServiceCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/Dashboard/ServicesList`; params?: Router.UnknownInputParams; } | { pathname: `/components/Dashboard/TopNavigation`; params?: Router.UnknownInputParams; } | { pathname: `/components/Dashboard/TransactionCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/Dashboard/TransactionsList`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/TopNavigation`; params?: Router.UnknownInputParams; };
    }
  }
}
